name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Copy repos
        uses: actions/checkout@v2

      - name: Download Liberica JDK 8
        run: |
          download_url="https://download.bell-sw.com/java/8u292+10/bellsoft-jdk8u292+10-linux-amd64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Setup Liberica JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '8'
          architecture: x86

      - name: Run java version
        run: |
          javac -source 8 -target 8 $GITHUB_WORKSPACE/dl4j-labs/src/main/java/ai/certifai/solution/convolution/mnist/MnistClassifier.java
          mvn -B -U verify